//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int id { get; set; }
        public int studentID { get; set; }
        public int testing_value { get; set; }
        public int share_value { get; set; }
        public int atendance_value { get; set; }
        public int shafahi_value { get; set; }
        public int homework_value { get; set; }
        public int subject_id { get; set; }
        public int user_id { get; set; }
        public int month_id { get; set; }
        public string note { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual MONTH MONTH { get; set; }
        public virtual Subjects Subject { get; set; }
        public virtual Users User { get; set; }
    }
}
