//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Managers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Managers()
        {
            this.Teachers = new HashSet<Teachers>();
        }
    
        public int ManagerID { get; set; }
        public string FullName_FirstName { get; set; }
        public string FullName_SecondName { get; set; }
        public string FullName_ThirdName { get; set; }
        public string FullName_LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Age { get; set; }
        public int SchoolID { get; set; }
        public int UserID { get; set; }
    
        public virtual Schools Schools { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teachers> Teachers { get; set; }
    }
}
