//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salarys
    {
        public int SalaryID { get; set; }
        public System.DateTime SalaryMonth { get; set; }
        public System.DateTime SalaryHireDate { get; set; }
        public string Note { get; set; }
        public int SalaryAmount { get; set; }
        public int TeacherID { get; set; }
    
        public virtual Teachers Teachers { get; set; }
    }
}
